import requests
from pprint import pprint

port = 5000                             # port at localhost where backend is running
session_id = '5b4944f80df44dd4'         # unique session ID (e.g. generated by os.urandom(8).hex())
API = "http://localhost:" + str(port) + "/api/"
file_zip = "Examples/Construct model/ascitic-fluid_bacteria_minimal.zip"

cookies = {"session_ramanmetrix_" + str(port): session_id}

# set some parameters
response = requests.post(url=API + "defaults", cookies=cookies,
                         json={'baseline_type': 'snip', 'baseline_iterations': 35})  # update parameters
pprint(response.json(), depth=1)  # print parameters that are set at the server from the response

# load training data
response = requests.post(url=API + "upload", cookies=cookies, files={"file": open(file_zip, 'rb')})
result = {"upload": response.json()}

# process data and train the model
for action in ["despike_data", "calibrate_data", "bg_correct_data", "normalize_data", "train_model"]:
    response = requests.post(url=API + action, cookies=cookies,
                             json={})  # update parameters at any step
    result[action] = response.json()
pprint(result, depth=2)     # print results summary

# export trained model
response = requests.post(url=API + 'model_download', cookies=cookies)
open('Examples/Construct model/custom_model.pkl', 'wb').write(response.content)
