import requests
from pprint import pprint

# first start "raman_backend.exe" from the directory "%LocalAppData%/Programs/Raman Analyst/server"
# alternatively, start the version of the software with GUI from the link on a desktop

port = 5000                             # port where backend is running (use port 5001 for the version with GUI)
session_id = '5b4944f80df44dd4'         # unique session ID (e.g. generated by os.urandom(8).hex())
API = "http://localhost:" + str(port) + "/api/"

file_zip = "Examples/Predict test data/ascitic-fluid_bacteria_minimal_test.zip"
file_model = "Examples/Predict test data/model_LDA_species.pkl"

cookies = {"session_ramanmetrix_" + str(port): session_id}

# get (initialize) default parameters
response = requests.post(url=API + "defaults", cookies=cookies)
response.json()

# load model
response = requests.post(url=API + "model_upload", cookies=cookies, files={"file": open(file_model, 'rb')})
result = {"model_upload": response.json()}

# load test data (as file)
response = requests.post(url=API + "upload_test", cookies=cookies, files={"file": open(file_zip, 'rb')})
result = {"upload_test": response.json()}
# process data and predict the data (if loaded as file)
for action in ["get_mean_raw_test", "test_prpr", "test_model"]:
    response = requests.post(url=API + action, cookies=cookies)
    result[action] = response.json()
pprint(result, depth=2)     # print results summary

# send, process and predict data loaded as JSON POST request (single API)
data = json.load(open('Use backend APIs/data.json', 'r'))
response = requests.post(url=API + "predict_json", cookies=cookies, json=data)
pprint(response.json(), depth=2)
